<?php

namespace App\Service;

use Symfony\Component\HttpClient\HttpClient;
use Exception;

class PostService
{
    private $apiUrl;
    private $httpClient;

    public function __construct(string $apiUrl)
    {
        $this->apiUrl = $apiUrl;
        $this->httpClient = HttpClient::create([
            'verify_peer' => false,
            'verify_host' => false,
        ]);
    }

    public function getPostsList()
    {
        try {
            $response = $this->httpClient->request('GET', $this->apiUrl . '/posts');
            $data = $response->toArray();

            return $data['hydra:member'];
        } catch (\Exception $exception) {
            // throw new Exception($exception->getMessage());
        }
    }

    public function getOnePost($id)
    {
        try {
            $response = $this->httpClient->request('GET', $this->apiUrl . '/posts/' . $id);
            $data = $response->toArray();

            return $data;
        } catch (\Exception $exception) {
            // throw new Exception($exception->getMessage());
        }
    }

    public function createPost($data)
    {
        try {
            $response = $this->httpClient->request('POST', $this->apiUrl . '/posts', [
                'json' => $data,
            ]);
            $data = $response->toArray();

            return $data;
        } catch (\Exception $exception) {
            throw new Exception($exception->getMessage());
        }
    }

    public function updatePost($id, $data)
    {
        try {
            $response = $this->httpClient->request('PUT', $this->apiUrl . '/posts/' . $id, [
                'json' => $data,
            ]);
            $data = $response->toArray();
    
            return $data;
        } catch (\Exception $exception) {
            throw new Exception($exception->getMessage());
        }
    }

    public function delete($id)
    {
        try {
            $response = $this->httpClient->request('DELETE', $this->apiUrl . '/posts/' . $id);
            $data = $response->toArray();

            return $data;
        } catch (\Exception $exception) {
            // throw new Exception($exception->getMessage());
        }
    }
}
